
```{r}
library(tidyverse)
library(readr)
library(ggplot2)
library(ggrepel)
```


```{r}
knownResults <- read_delim("~/Dropbox/Work/ATAC-seq/atac_veronica/data/motif/more_accessible_in_KO/knownResults.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)

head(knownResults)
```

```{r}
knownResults$rank <- 1:nrow(knownResults)

plot_log2 <-ggplot(subset(knownResults, rank <1000), aes(x=rank,
                                                         y=-log2(`P-value`), label=`Motif Name`))+
  geom_point(size=0.1, position=position_jitter(h=0.3, w=0.5), shape = 21, alpha = 0.5, size = 3)+
  geom_point(data=subset(knownResults, rank <3), color="red")+
  geom_text(data=subset(knownResults, rank <3), position = position_nudge(x = 400) )+
  xlab("Motif rank")+
  ylab("-log2 p-value")+
  theme(axis.line = element_line(colour = "black"),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank()
  )

plot_log2
```

```{r}
plot_log10 <-ggplot(subset(knownResults, rank <1000), aes(x=rank,
                                                          y=-log10(`P-value`), label=`Motif Name`))+
  geom_point(size=0.1, position=position_jitter(h=0.3, w=0.5), shape = 21, alpha = 0.5, size = 3)+
  geom_point(data=subset(knownResults, rank <3), color="red")+
  xlab("Motif rank")+
  ylab("-log10 p-value")+
  theme(axis.line = element_line(colour = "black"),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank()) +
  geom_text(data=subset(knownResults, rank <3), position = position_nudge(x = 400) )

plot_log10


```
```{r}
ggsave(plot_log2, filename = "~/Dropbox/Work/ATAC-seq/atac_veronica/data/motif/Log2_Ranked_motif_more_accessible.pdf", dpi = 600)
ggsave(plot_log10, filename = "~/Dropbox/Work/ATAC-seq/atac_veronica/data/motif/Log10_Ranked_motif_more_accessible.pdf", dpi = 600)
```

