**Note:** Remember to create a "data/" and a "output/" folder in the current directory.
Install packages.
```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("TxDb.Mmusculus.UCSC.mm10.knownGene")
library(TxDb.Mmusculus.UCSC.mm10.knownGene)
```

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ChIPseeker")
library(ChIPseeker)
```

If
```{r}
wd <- getwd()
path_to_input= file.path(wd, "data")
path_to_output= file.path(wd, "output")
pattern=".narrowPeak" #.narrowPeak
txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene
samplefiles <- list.files(path = path_to_input, pattern = pattern, full.names = T)
samplefiles <- as.list(samplefiles)
filenames <- gsub(file.path(wd, "data", "*"), "", samplefiles) 
filenames <- gsub("*.narrowPeak", "", filenames)
names(samplefiles) <- filenames
peakAnnoList <- lapply(samplefiles, annotatePeak, TxDb=txdb, verbose = F)
pdf(file = paste0(path_to_output, "/annotations_plot.pdf"))
plotAnnoBar(peakAnnoList)
dev.off()
SaveTable <- function(n){
  anno <- data.frame(peakAnnoList[[n]]@anno)
  write.table(anno, file = paste0(wd, "/output/", filenames[n], "_anno.xls"), sep = "\t")}

lapply(1:length(samplefiles), SaveTable)
```